title: 3dsCompatTest

Description: A website used for testing the compatibility of the 3ds web browser.
It was built to test its speed and perfomance when handling modern or newer website structuring and processing.
